theme = "sonokai"

[editor]
line-number = "absolute"
mouse = false
cursorline = true
true-color = true
idle-timeout = 0
completion-trigger-len = 1

[editor.cursor-shape]
insert = "underline"
normal = "block"
select = "bar"

[editor.lsp]
display-messages = true
display-inlay-hints = false

[editor.indent-guides]
render = true